### PR TITLE
Adding chemistry functions

### PR DESCRIPTION
**Pull request by florisvdh**

### CODE REVIEW

**Comment by florisvdh** [comment]
Currently, the intended functions on chemical data have been added. (And with that, all currently intended functions)

- `get_chem()` retrieves data
- `eval_chem()` returns summary statistics (availability and numeric properties) based on `get_chem()` output
- `selectlocs_chem()` allows the user to select locations that meet certain conditions (to be provided by the user). Conditions refer to the summary statistics. As input, the output of `get_chem()` or `eval_chem()` can be used.

The functions can be explored by means of the examples:

- `example("get_chem", run.dontrun = TRUE)`
- etc.

**Comment by w-jan** [comment]
hello Floris,

Another piece of excellent work ! Thanks !
here a quick review of the get_chem-function:
Retrieving is OK, except : when strict_en = TRUE, variables that are EN-independent (pH, cond) are also excluded.
Lab_project_id is always 0, probably it isn't used in the datasource Watina ?
log is always -99, for the same reason ?
Formatting Value-field: if the conc_type is mg/l then 2-3 digits will be enough.
For pHF the below_loq = NA, for pHL = FALSE: I would expect that it would be the same for both (= NA)
I suggest to use a percentage (integer) as format for elneutr in stead of a floating point: it's more readable.
The units of the conductivity are in my case not good presented ('<U+00B5>S/cm
') ( is an UTF-translation matter ?).

greetings,
Jan

**Comment by florisvdh** [comment]
Many thanks for the review and for posting the issue (#22) @w-jan :+1:  . You have good senses :wink:. I'll come back with answers / solutions (some have a simple answer, some need a bit more investigation).

**Comment by florisvdh** [comment]
@w-jan I've looked a bit further. I concluded to withhold your first bullet (see issue #22), which is actually an issue with the handling of the `en_range` argument (for both sides of `strict_en`).

Regarding your other points:

- labproject_id, loq, ... these are still missing from the datawarehouse, so that's for the future. Currently set as dummies.
- formatting is not relevant here. The returned object in R is for use in analyses by the user (R script, R markdown). It is the endresult of the user that must be formatted by him/herself. That can be the mere result of `get_chem()` etc., but then it is up to the user to do formatting. So rounding numbers or  percentage formatting is not an aim (and could be a pitfall in some cases).
- _For pHF the below_loq = NA, for pHL = FALSE_: the functions just return the contents of the database. Data problems must be solved there. It could be solved here of course, but that would be a workaround.
- The problem with Unicode characters may be somewhere in the combination of Windows + RStudio + the odbc-implementation of the odbc-package. Windows appears not support UTF-8 locale out-of-the box at system level (it uses its own), while it is the current standard in open science tools -- this makes it a challenge to developers. Even sorting order of strings differs between these locales. It seems that currently Windows 10 _does_ support UTF-8 in a _beta_ stage (you need to manually activate it, but is said to be unreliable). So some hope exists.

**Comment by florisvdh** [comment]
I was a bit rushing in my previous comment. I think the representation of electroneutrality needs some further discussion on Monday. I tend to use fractions to represent fractions because that is generally the way it is done.

Regarding Unicode, there is also [this page](https://support.rstudio.com/hc/en-us/articles/200532197-Character-Encoding) of RStudio about better Unicode support. But clearly, it is not without issues.

**Comment by florisvdh** [comment]
Commit f405fd8 should have fixed issue #23 . @w-jan can you verify this?

Also relevant to @ToonVanDaele @mathiaswackenier @fredericpiesschaert @cecileherr @maudraman @DriesAdriaens : the following should be implemented by this PR - further testing is welcomed:

- `get_locs()`:
  - return locations with status `VLD` or `ENT` by default
  - implements an argument `filterdepth_range` (default 0 to 3 meters below soil surface)
- `get_xg3()`:
  - optionally returns 'observation wells' (this matches 'PeilPunt' in the database) - other names are welcomed as these must also comprise the surface water level measurement devices
  - returns soil surface level (Ostend height CRS) and filter depth of the most recent observation well (optionally, per observation well)
- `get_chem()`:
  - argument `strict_en` has been renamed as `exclude_en_na`
  - always returns non-ion variables (irrespective of `en_range` and `exclude_en_na`)

**Comment by florisvdh** [comment]
Note that installation of `watina` from this branch will typically fail if done locally with `devtools::install()`. This is because, starting with commit cc24a72, the package needs `dbplyr` from another branch (see [this PR](https://github.com/tidyverse/dbplyr/pull/344)).

For now, it is advised to install from github with `remotes::install_github()`, as that will invoke the installation of this development version of `dbplyr`.

**Comment by florisvdh** [comment]
Merging here. This should update the [website](https://inbo.github.io/watina) to `watina` version `0.2.0` in a few minutes.

**Pull request merged**
